
security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        users:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            provider: users
            form_login:
                login_path: user_login
                check_path: user_login
            logout:
                path: /logout
                target: /login

    access_control:
        - { path: ^/event/add, roles: ROLE_USER }